### ISSUE TITLE
ijm-00002.xml <target> tag

### ISSUE THREAD

**Issue by gnott** [microsimulation/ijm-xml#20]
In converting file `ijm-00002.xml`, there are some `<target>` tags in the `<body>` which end up in the final output.

@Melissa37 do you know what these are please and how they should be treated please?

**Comment by Melissa37** [comment]
This is interesting, and is based on a print product :-)

The text at the top of the document has been converted to an author footnote:
```
<author-notes>
                <fn id="fn1-0">
                    <p>By permission of MIT Press reproduced below is the full text of Orcutt G
                        (1957) &#x2018;A new type of socio-economic system&#x2019;, <italic>Review
                            of Economics and Statistics</italic>, 39(2), 116&#x2013;123. The
                        original page numbering is indicated throughout the text in square brackets.
                        In the original all footnotes appeared on the page in which they were
                        alluded to in the text; here all footnotes appear on the final page.</p>
                </fn>
            </author-notes>
```
This is wrong. I think it should be abstract for our purposes.

Which leads us onto the target:
`<target id="page-116" target-type="pagenumber">[116]</target>`

JATS Explanation of a target: Anchor or fixed location that acts as the target for a cross-reference
**The original page numbering is indicated throughout the text in square brackets.** 

I think we could convert the targets to sec titles.

**Comment by Melissa37** [comment]
@ matteorichiardi FOR INFO

**Comment by Vijayarajmurugesan** [comment]
@Melissa37 

As you suggested, I have fixed the issue and uploaded below path:

https://exeterpremedia.exavault.com/share/view/1i5dm-9s6a5s81

Thanks,
Vijay

**Comment by Melissa37** [comment]
Thanks!

**Comment by Melissa37** [comment]
@gnott  can you reload this one, it's still appearing with this tagging:
![Screenshot 2019-05-17 at 15 14 13](https://user-images.githubusercontent.com/6051876/57934020-96268a80-78b6-11e9-95ee-22cee16663e4.png)

**Comment by gnott** [comment]
I am checking the resupply. The `<target>` tags are gone I think. There is a new validation issue though, which causes an error on the demo site as well. There are some `<sec>` tags with no `id` attribute. The schema seems to require all these to have an `id`. @Melissa37 if you could please confirm and either queue up for another resupply, or please open a new ticket regarding the `<sec>` tags on 00002 please? Thanks!

**Comment by Melissa37** [comment]
@Vijayarajmurugesan Please see Graham's comment above - There are some <sec> tags with no id attribute. The schema seems to require all these to have an id.

Can you check all the content and ensure all `<sec>`s have an id before resupplying any more? And can you resupply this one?

Thanks!

**Comment by Vijayarajmurugesan** [comment]
@Melissa37 I have fixed this issue. In future articles, we will ensure the section ids.
Please find the below link for resupply article:
https://exeterpremedia.exavault.com/share/view/1i5dm-9s6a5s81
Thanks,
Vijay

**Comment by gnott** [comment]
I am able to generate valid JSON from the most recently supplied XML, thanks Vijay!
